name: cyclone
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audio_service: ^0.17.1
  audio_session: ^0.1.2
  audioplayers: ^0.19.0
  auto_size_text: ^2.1.0
  bloc: ^7.0.0
  cached_network_image: ^3.0.0
  carousel_slider: ^3.0.0
  cloud_firestore: ^2.2.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.0
  dio: ^4.0.0
  epub_viewer: ^0.2.1
  eva_icons_flutter: ^3.0.0
  extended_image: ^4.0.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  firebase_messaging: ^10.0.0
  firebase_storage: ^8.1.0
  flutter_dialogs: ^1.0.3
  flutter_downloader: 1.5.2
  flutter_facebook_login: ^3.0.0
  # flutter_html: ^1.3.0
  flutter_icons: ^1.1.0
  flutter_inner_drawer: ^1.0.0+1
  flutter_launcher_icons: ^0.9.0
  flutter_local_notifications: ^6.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: any
  fluttertoast: ^8.0.7
  fradio: ^1.0.1
  google_sign_in: any
  html: ^0.14.0+4
  http: ^0.13.3
  image_picker: ^0.7.5+3
  just_audio: ^0.7.4
  logging: ^1.0.1
  marquee: ^2.1.0
  mockito: ^5.0.9
  modal_bottom_sheet: ^2.0.0
  mp3_info: ^0.2.0
  objectdb: ^1.0.7+1
  path_provider: any
  percent_indicator: ^3.0.1
  permission_handler: ^8.0.0+2
  photo_view: ^0.10.2
  podcast_search: ^0.4.0
  provider: ^5.0.0
  rxdart: ^0.27.0
  scrollable_positioned_list: ^0.1.10
  sembast: ^3.0.2
  share: ^2.0.4
  shared_preferences: ^2.0.5
  timeago: ^3.0.2
  top_snackbar_flutter: ^1.0.0
  url_launcher: ^6.0.4
  uuid: ^3.0.4
  webview_flutter: ^1.0.7
  xml2json: ^5.1.0
  youtube_player_flutter: ^8.0.0
  dcdg: ^3.1.1
  firebase_ml_custom: ^0.2.0+1
  # tflite_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/images/
    - assets/logos/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
    - family: SpaceMonoRegular
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
    - family: SpaceMonoBold
      fonts:
        - asset: assets/fonts/SpaceMono-Bold.ttf
    - family: RobotoCondensedBold
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
    - family: JostRegular
      fonts:
        - asset: assets/fonts/jost/Jost-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
