name: Siuu
description: Social Network

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  animated_background: ^1.0.5
  audio_wave: ^0.0.3
  audioplayers: ^0.19.1
  auto_size_text: ^2.1.0
  auto_size_text_field: ^0.1.7
  back_button_interceptor: ^4.0.1
  cached_network_image: ^2.2.0+1
  carousel_slider: ^2.3.1
  clippy_flutter: ^1.1.1
  cloud_firestore: ^2.4.0
  connectivity: ^3.0.6
  cupertino_icons: ^0.1.2
  custom_info_window: ^1.0.1
  dcache: ^0.1.0
  device_info: ^0.4.0+1
  emojis: ^0.9.3
  exif: ^2.0.0
  expandable: ^5.0.1
  file_picker: ^3.0.3
  firebase_auth: ^2.0.0
  firebase_core: ^1.0.2
  firebase_messaging: ^10.0.6
  firebase_storage: ^10.0.2
  fluster: ^1.2.0
  flutter:
    sdk: flutter
  flutter_advanced_networkimage:
    git:
      url: https://github.com/ramazanyigitt/flutter_advanced_networkimage
  flutter_audio_recorder2: ^0.0.2
  flutter_better_camera: ^1.0.2+1
  flutter_bloc: ^7.1.0
  flutter_cache_manager: ^2.0.0
  flutter_colorpicker: ^0.3.5
  flutter_countdown_timer: ^3.0.0
  flutter_fadein: ^1.1.1
  flutter_ffmpeg: ^0.3.1
  flutter_google_places: ^0.2.8
  flutter_image_compress: ^1.0.0
  flutter_keyboard_visibility: ^5.0.2
  flutter_local_notifications: ^8.1.1+1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.2
  flutter_pagewise: ^1.2.2
  flutter_reaction_button: ^1.0.6+1
  flutter_record_plugin:
    git:
      url: https://github.com/ramazanyigitt/flutter_record_plugin
  flutter_secure_storage: ^3.1.2
  flutter_slidable: ^0.6.0
  flutter_socket_io: ^0.6.0
  flutter_sound: ^8.1.1
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  flutter_swipe_action_cell: ^2.1.1
  flutter_xlider: ^3.4.0
  fluttertoast: ^8.0.8
  geocoder: ^0.2.1
  geolocator: ^7.4.0
  gesture_x_detector: ^1.0.0
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.6
  google_maps_webservice: ^0.0.20-nullsafety.5
  html: ^0.14.0+2
  http: ^0.13.0
  http_retry: ^0.2.0
  hydrated_bloc: ^7.0.1
  image_cropper: ^1.2.2
  image_picker: ^0.8.1+3
  intercom_flutter: ^2.0.5+2
  intl: ^0.17.0
  inview_notifier_list: ^2.0.0
  keyboard_attachable: ^2.0.1
  keyboard_visibility: ^0.5.6
  location: ^4.3.0
  lottie: ^1.1.0
  mime: ^0.9.6+2
  modal_bottom_sheet: ^2.0.0
  onesignal_flutter: ^2.2.0
  open_iconic_flutter: ^0.3.0
  package_info: ^0.4.0
  path: ^1.7.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  photo_view: ^0.12.0
  pigment: ^1.0.3
  pin_entry_text_field: ^0.1.4
  public_suffix: ^1.2.0
  pull_to_refresh: ^2.0.0
  retry: ^3.1.0
  roundcheckbox: ^1.0.0
  rounded_loading_button: ^1.0.18
  rxdart: ^0.25.0
  screen: ^0.0.5
  scroll_to_index: ^2.0.0
  sentry: ^5.1.0
  share: ^0.6.4
  shared_preferences: ^2.0.6
  shimmer: ^1.0.0
  sleek_circular_slider: ^1.2.0+web
  sprintf: ^6.0.0
  story_view: ^0.12.8
  swipe_to: ^0.0.1+8
  swipe_up: ^1.0.0
  throttling: ^0.8.0
  timeago: ^2.0.9
  tinycolor: ^1.0.2
  uni_links: ^0.2.0
  url_launcher: ^4.0.1
  uuid: ^3.0.4
  validators: ^3.0.0
  video_player: ^1.0.1
  video_thumbnail: ^0.3.3
  visibility_detector: ^0.2.0
  wakelock: ^0.1.3
  firestore_cache: ^2.1.1
  declarative_animated_list: ^0.1.1

dependency_overrides:
  cached_network_image: ^3.0.0
  flutter_cache_manager: ^3.0.0
  html: ^0.15.0
  simple_url_preview: ^3.0.1
  linkable: ^3.0.1
  url_launcher: ^6.0.10
  rxdart: ^0.27.0
  geoflutterfire: ^3.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/images/icon-adaptive-foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/fallbacks/
    - assets/images/theme-previews/
    - assets/other/
    - assets/svg/
    - assets/lottie/
    - assets/sorted_lotties/
    - assets/sorted_lotties/lottie/
    - assets/map_style.json
    - assets/env.json
    - assets/countrycodes.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          style: normal
        - asset: assets/fonts/NunitoSans-Bold.ttf
          style: italic
    - family: VisbyRoundCF
      fonts:
        - asset: assets/fonts/VisbyRoundCF-Regular.otf
          style: normal
        - asset: assets/fonts/VisbyRoundCF-Bold.otf
          style: italic
    - family: CogogooseProSemilight
      fonts:
        - asset: assets/fonts/Cocogoose-Pro-Semilight.ttf
          style: normal
    - family: ''
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
          style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
